In [4]:
# Cell 1
import pandas as pd

In [5]:
# Cell 2 — load & parse
df = pd.read_csv('simulados_clean.csv')
df['created_at'] = pd.to_datetime(df['created_at'])
df.head()

,id,aluno_id,nome,data,matematica,linguagens,humanas,natureza,redacao_total,redacao_c1,redacao_c2,redacao_c3,redacao_c4,redacao_c5,created_at
0,43f44222-d31e-4735-a28e-354491af4a56,05eebd85-ad17-4d43-934f-1cbce6cf446f,Enem 2025,2026-01-01,22.0,29.0,31.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-02 18:01:44.226071+00:00
1,686ddcf1-dc8b-4176-a8f1-84c1e3dfbf07,05eebd85-ad17-4d43-934f-1cbce6cf446f,Bernoulli 1° Conjunto 2025,2026-01-01,35.0,NaN,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-02 18:01:44.226071+00:00
2,772b8a31-5c88-4a4a-95a4-9a031e0c5c7e,05eebd85-ad17-4d43-934f-1cbce6cf446f,Bernoulli 2° Conjunto 2025,2026-01-01,NaN,27.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-02 18:01:44.226071+00:00
3,89d250a0-e07e-45d8-9cd6-cc1b30e1214f,05eebd85-ad17-4d43-934f-1cbce6cf446f,Bernoulli 3° Conjunto 2025,2026-01-01,32.0,28.0,30.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-02 18:01:44.226071+00:00
4,933dda76-cf83-4372-bbdd-3ff7384dc665,05eebd85-ad17-4d43-934f-1cbce6cf446f,Bernoulli 1° Conjunto 2026,2026-01-01,25.0,30.0,32.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-02 18:01:44.226071+00:00

In [6]:
# Cell 3 — detect clusters
df['cluster_size'] = df.groupby(['aluno_id', 'created_at'])['created_at'].transform('size')
df['cluster_size'].value_counts()

cluster_size
1     134
3      15
4      12
5      10
10     10
2       8
7       7
6       6
Name: count, dtype: int64

In [7]:
# Cell 4 — split
unique_rows = df[df['cluster_size'] == 1].copy()
clustered_rows = df[df['cluster_size'] > 1].copy()
len(unique_rows), len(clustered_rows)

(134, 68)

In [8]:
# Cell 5 — collapse
areas = ['matematica', 'linguagens', 'humanas', 'natureza']
collapsed = clustered_rows.groupby(['aluno_id', 'created_at'], as_index=False)[areas].mean()
collapsed

,aluno_id,created_at,matematica,linguagens,humanas,natureza
0,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-04-02 18:01:44.226071+00:00,25.166667,29.833333,31.833333,25.000000
1,2119aaa5-f0a9-4cb8-bc30-3a5504efd77d,2026-04-02 18:02:20.834051+00:00,27.250000,37.500000,35.500000,30.500000
2,233afb42-cb42-41fe-a7fc-e865bc9615f1,2026-04-02 18:03:09.537022+00:00,24.000000,26.000000,29.000000,21.500000
3,3e34a61b-98e0-48c8-951e-c9cf83a78c41,2026-04-02 18:01:52.603871+00:00,31.750000,35.250000,33.500000,32.000000
4,41180d34-1434-4ee9-88f1-d12766ceb207,2026-04-02 18:02:12.826136+00:00,40.000000,33.000000,31.666667,34.666667
5,4d3ee5f1-21e1-444d-94fd-d3d0832f0ea6,2026-04-02 18:02:35.862408+00:00,36.000000,36.500000,37.000000,33.500000
6,53f74b3a-3973-4af8-a567-55ce939243ac,2026-04-02 18:02:27.756899+00:00,30.500000,31.500000,32.750000,21.000000
7,58d56284-c5de-4e5a-beff-b81975b6c09a,2026-04-02 18:02:51.119169+00:00,25.333333,32.666667,31.333333,28.666667
8,5a37ed4e-7ba3-41e9-86e2-aff4f4b021e1,2026-04-02 18:02:03.897556+00:00,28.333333,31.777778,32.111111,30.375000
9,5aa85d64-c555-428b-bd7f-a226396a05dc,2026-04-02 18:03:24.419731+00:00,32.000000,35.400000,38.600000,29.750000
10,61c26d20-94a0-42e8-abd6-43c2adf0794b,2026-04-02 18:01:17.157068+00:00,41.000000,29.000000,40.000000,31.000000
11,78b11991-11c8-4598-b575-4331c72511e1,2026-04-02 18:01:23.756801+00:00,33.000000,25.000000,25.000000,27.000000
12,8089b383-82f8-4465-a2f0-89e8f1841d24,2026-04-02 18:01:10.129950+00:00,36.000000,17.000000,31.000000,29.000000
13,ab27c6c6-9995-4310-9746-ea7606df8e56,2026-04-02 18:03:45.970249+00:00,NaN,39.666667,39.666667,NaN
14,ae2ab9aa-c61d-4df0-9df7-b8b74b841471,2026-04-02 18:02:42.216462+00:00,32.000000,37.500000,33.500000,34.250000
15,d67f8842-31bb-421d-8b0e-0bf96e1164b5,2026-04-02 18:01:32.991828+00:00,21.000000,29.000000,27.000000,23.666667
16,e747b89c-ae5b-440f-ab3f-05088af5b560,2026-04-02 18:03:02.065831+00:00,26.500000,38.500000,35.000000,31.000000

In [9]:
# Cell 6 — merge & sort
unique_trimmed = unique_rows[['aluno_id', 'created_at'] + areas]
final_df = pd.concat([unique_trimmed, collapsed], ignore_index=True)
final_df = final_df.sort_values(['aluno_id', 'created_at']).reset_index(drop=True)
final_df.head(15)

,aluno_id,created_at,matematica,linguagens,humanas,natureza
0,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-04-02 18:01:44.226071+00:00,25.166667,29.833333,31.833333,25.0
1,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-04-27 19:08:54.183793+00:00,NaN,NaN,NaN,NaN
2,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-04-28 01:32:38.720997+00:00,25.000000,NaN,NaN,21.0
3,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-05-06 20:37:03.468013+00:00,24.000000,NaN,NaN,NaN
4,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-06-08 23:10:21.903540+00:00,24.000000,27.000000,33.000000,25.0
5,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-06-08 23:17:19.204186+00:00,31.000000,23.000000,38.000000,25.0
6,1685cd68-0db4-41e2-84f7-5065022bb134,2026-04-02 18:23:16.513865+00:00,41.000000,40.000000,40.000000,39.0
7,1685cd68-0db4-41e2-84f7-5065022bb134,2026-04-16 03:14:41.350139+00:00,35.000000,33.000000,35.000000,31.0
8,1685cd68-0db4-41e2-84f7-5065022bb134,2026-04-16 03:14:58.045098+00:00,29.000000,28.000000,35.000000,20.0
9,1685cd68-0db4-41e2-84f7-5065022bb134,2026-04-16 14:00:21.149869+00:00,42.000000,39.000000,38.000000,44.0
10,1685cd68-0db4-41e2-84f7-5065022bb134,2026-04-16 14:00:56.863694+00:00,43.000000,39.000000,41.000000,42.0
11,2119aaa5-f0a9-4cb8-bc30-3a5504efd77d,2026-04-02 18:02:20.834051+00:00,27.250000,37.500000,35.500000,30.5
12,2119aaa5-f0a9-4cb8-bc30-3a5504efd77d,2026-05-04 17:02:57.073794+00:00,30.000000,39.000000,35.000000,33.0
13,2119aaa5-f0a9-4cb8-bc30-3a5504efd77d,2026-05-21 16:25:08.436689+00:00,32.000000,36.000000,36.000000,30.0
14,2119aaa5-f0a9-4cb8-bc30-3a5504efd77d,2026-05-26 16:17:25.061295+00:00,35.000000,38.000000,41.000000,35.0

In [10]:
# Cell 7 — drop empties
fully_empty = final_df[areas].isnull().all(axis=1)
final_df = final_df[~fully_empty].reset_index(drop=True)
len(final_df)

148

In [11]:
# Cell 8 — verify & save
final_df.duplicated(subset=['aluno_id', 'created_at'], keep=False).sum()

np.int64(0)

In [12]:
# Cell 9
final_df.to_csv('simulados_paired_ready.csv', index=False)

In [13]:
# Cell 10 — pull out one student's full history to inspect, in order
grouped = final_df.groupby('aluno_id')

# pick the first student id that appears in the data
one_student_id = final_df['aluno_id'].iloc[0]

# .get_group() pulls out just that student's rows from the grouped object
one_student = grouped.get_group(one_student_id)
one_student

,aluno_id,created_at,matematica,linguagens,humanas,natureza
0,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-04-02 18:01:44.226071+00:00,25.166667,29.833333,31.833333,25.0
1,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-04-28 01:32:38.720997+00:00,25.000000,NaN,NaN,21.0
2,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-05-06 20:37:03.468013+00:00,24.000000,NaN,NaN,NaN
3,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-06-08 23:10:21.903540+00:00,24.000000,27.000000,33.000000,25.0
4,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-06-08 23:17:19.204186+00:00,31.000000,23.000000,38.000000,25.0

In [21]:
# Cell 11 — build prev/next pairs for just this one student first, to check the logic

one_student = one_student.reset_index(drop=True)  
# reset_index gives this student's rows clean positions 0, 1, 2...
# (without this, .iloc and .loc could disagree, since the original index 
# numbers came from the full 148-row dataframe, not from 0)

pairs = []  # will hold one dictionary per training pair

for i in range(len(one_student) - 1):
    # -1 because the very last test has no "next" test after it —
    # it can only ever be used as a target, never as an input
    
    prev_test = one_student.iloc[i]      # the earlier test in this pair (a single row)
    next_test = one_student.iloc[i + 1]  # the later test in this pair

    pair_row = {
        'aluno_id': one_student.loc[i, 'aluno_id'],
        'prev_matematica': prev_test['matematica'],
        'prev_linguagens': prev_test['linguagens'],
        'prev_humanas': prev_test['humanas'],
        'prev_natureza': prev_test['natureza'],
        'next_matematica': next_test['matematica'],
        'next_linguagens': next_test['linguagens'],
        'next_humanas': next_test['humanas'],
        'next_natureza': next_test['natureza'],
    }
    pairs.append(pair_row)

pairs_df = pd.DataFrame(pairs)
pairs_df

,aluno_id,prev_matematica,prev_linguagens,prev_humanas,prev_natureza,next_matematica,next_linguagens,next_humanas,next_natureza
0,05eebd85-ad17-4d43-934f-1cbce6cf446f,25.166667,29.833333,31.833333,25.0,25.0,NaN,NaN,21.0
1,05eebd85-ad17-4d43-934f-1cbce6cf446f,25.000000,NaN,NaN,21.0,24.0,NaN,NaN,NaN
2,05eebd85-ad17-4d43-934f-1cbce6cf446f,24.000000,NaN,NaN,NaN,24.0,27.0,33.0,25.0
3,05eebd85-ad17-4d43-934f-1cbce6cf446f,24.000000,27.000000,33.000000,25.0,31.0,23.0,38.0,25.0

In [27]:
# Cell 12 — repeat the pairing logic for every student, not just one

all_pairs = []  # will collect every pair, from every student

for aluno_id, group in final_df.groupby('aluno_id'):
    # iterating directly over a groupby object gives you (key, group) pairs —
    # aluno_id is the student's id, group is that student's rows (same as 
    # what .get_group() gave you in Cell 10, just looped automatically)

    group = group.reset_index(drop=True)  # same reason as before

    for i in range(len(group) - 1):
        prev_test = group.iloc[i]
        next_test = group.iloc[i + 1]

        pair_row = {
            'aluno_id': aluno_id,
            'prev_created_at': prev_test['created_at'],
            'prev_matematica': prev_test['matematica'],
            'prev_linguagens': prev_test['linguagens'],
            'prev_humanas': prev_test['humanas'],
            'prev_natureza': prev_test['natureza'],
            'next_matematica': next_test['matematica'],
            'next_linguagens': next_test['linguagens'],
            'next_humanas': next_test['humanas'],
            'next_natureza': next_test['natureza'],
        }
        all_pairs.append(pair_row)

pairs_df = pd.DataFrame(all_pairs)
pairs_df

,aluno_id,prev_created_at,prev_matematica,prev_linguagens,prev_humanas,prev_natureza,next_matematica,next_linguagens,next_humanas,next_natureza
0,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-04-02 18:01:44.226071+00:00,25.166667,29.833333,31.833333,25.000000,25.0,NaN,NaN,21.0
1,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-04-28 01:32:38.720997+00:00,25.000000,NaN,NaN,21.000000,24.0,NaN,NaN,NaN
2,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-05-06 20:37:03.468013+00:00,24.000000,NaN,NaN,NaN,24.0,27.0,33.0,25.0
3,05eebd85-ad17-4d43-934f-1cbce6cf446f,2026-06-08 23:10:21.903540+00:00,24.000000,27.000000,33.000000,25.000000,31.0,23.0,38.0,25.0
4,1685cd68-0db4-41e2-84f7-5065022bb134,2026-04-02 18:23:16.513865+00:00,41.000000,40.000000,40.000000,39.000000,35.0,33.0,35.0,31.0
...,...,...,...,...,...,...,...,...,...,...
110,d67f8842-31bb-421d-8b0e-0bf96e1164b5,2026-04-02 18:01:32.991828+00:00,21.000000,29.000000,27.000000,23.666667,25.0,36.0,31.0,22.0
111,d67f8842-31bb-421d-8b0e-0bf96e1164b5,2026-04-29 00:26:33.602052+00:00,25.000000,36.000000,31.000000,22.000000,27.0,38.0,32.0,28.0
112,e747b89c-ae5b-440f-ab3f-05088af5b560,2026-04-02 18:03:02.065831+00:00,26.500000,38.500000,35.000000,31.000000,25.0,42.0,39.0,33.0
113,e747b89c-ae5b-440f-ab3f-05088af5b560,2026-04-07 00:18:45.909941+00:00,25.000000,42.000000,39.000000,33.000000,35.0,36.0,39.0,36.0
114,e747b89c-ae5b-440f-ab3f-05088af5b560,2026-04-12 12:18:10.221575+00:00,35.000000,36.000000,39.000000,36.000000,33.0,40.0,39.0,26.0

In [16]:
pairs_df['aluno_id'].nunique()

25

In [22]:
# Cell 13 — find which students have only 1 test (contributed no pairs)

students_in_pairs = pairs_df['aluno_id'].unique()
all_students = final_df['aluno_id'].unique()

missing = [s for s in all_students if s not in students_in_pairs]
print(f"{len(missing)} students with only 1 test: {missing}")

# also useful: see the test count distribution across all students
final_df.groupby('aluno_id').size().value_counts().sort_index()

32 students with only 1 test: ['1685cd68-0db4-41e2-84f7-5065022bb134', '2119aaa5-f0a9-4cb8-bc30-3a5504efd77d', '233afb42-cb42-41fe-a7fc-e865bc9615f1', '2a136dad-e4c5-4de8-b4b1-fb18788a8f44', '2d95dc73-c750-4806-a7cf-0deb07faad30', '3e34a61b-98e0-48c8-951e-c9cf83a78c41', '41180d34-1434-4ee9-88f1-d12766ceb207', '4d3ee5f1-21e1-444d-94fd-d3d0832f0ea6', '4e8115b5-3e5b-439c-867b-a876befcdea4', '53f74b3a-3973-4af8-a567-55ce939243ac', '58d56284-c5de-4e5a-beff-b81975b6c09a', '5a37ed4e-7ba3-41e9-86e2-aff4f4b021e1', '5aa85d64-c555-428b-bd7f-a226396a05dc', '5b152cab-3b5e-43c2-8491-f5c88ef7d9f5', '5ec1c4b5-3321-45c2-b268-161da203607d', '61c26d20-94a0-42e8-abd6-43c2adf0794b', '64936158-5ae8-48cf-b5cd-c6c4d0aabcd9', '66fe1554-753a-4fd2-89a0-b7a8fdf52587', '724a4bd8-fd21-401a-bf6c-4bb541054faa', '78b11991-11c8-4598-b575-4331c72511e1', '8089b383-82f8-4465-a2f0-89e8f1841d24', '8b7fa671-82e2-4a57-90d8-cbd0b92001f8', '9c09a49b-5fee-48a1-9710-64f74255b56d', '9efd46a8-b99a-4474-9d41-1a7fc6ba63a4', 'ab27c6c6-9995-4310-9746-ea7606df8e56', 'ae2ab9aa-c61d-4df0-9df7-b8b74b841471', 'b98b036c-56cf-4167-932b-4e8cafb4218d', 'c80db275-3edd-49bb-ab16-4f7e9e16dd90', 'd67f8842-31bb-421d-8b0e-0bf96e1164b5', 'e747b89c-ae5b-440f-ab3f-05088af5b560', 'e78698d6-8ff9-4644-9a25-24ba0d1aca10', 'f298374e-5090-4830-86da-69f5e2b4addb']

1     8
2     5
3     2
4     4
5     4
6     2
7     3
8     1
9     2
12    1
17    1
Name: count, dtype: int64

In [28]:
# Cell 14 — save pairs_df as a checkpoint before building features

pairs_df.to_csv('simulados_pairs.csv', index=False)
print(f"Saved {len(pairs_df)} pairs from {pairs_df['aluno_id'].nunique()} students")

Saved 115 pairs from 25 students

In [19]:
# run this in 01_clean_and_pair.ipynb to see what's in pairs_df before saving
print(pairs_df.columns.tolist())

['aluno_id', 'prev_created_at', 'prev_matematica', 'prev_linguagens', 'prev_humanas', 'prev_natureza', 'next_matematica', 'next_linguagens', 'next_humanas', 'next_natureza']